[package]
name = "scyllash"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
color-eyre = "0.6.3"
ratatui = { version = "0.28.0", features = ["all-widgets"] }
scylla = "0.13.2"
tokio = { version = "1.39.3", features = ["full"] }
uuid = { version = "1.10.0", features = ["v1", "v4"] }
